import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./Components/Navbar/Navbar";
import { Header } from "./Components/MainPage/Header/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
